"""program_session

Revision ID: c68142a1223d
Revises: d54e8c97a8a4
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c68142a1223d'
down_revision: Union[str, None] = 'd54e8c97a8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_session',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('place_id', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.String(length=40), nullable=False),
    sa.Column('ends_at', sa.String(length=40), nullable=False),
    sa.Column('session_day_kst', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancel_reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint("status = 'scheduled' OR cancel_reason <> ''", name=op.f('ck_program_session_cancel_reason')),
    sa.CheckConstraint("status IN ('scheduled','canceled')", name=op.f('ck_program_session_status')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_program_session_times')),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_program_session_place_id_place')),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_program_session_program_id_program')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_session'))
    )
    with op.batch_alter_table('program_session', schema=None) as batch_op:
        batch_op.create_index('ix_program_session_day', ['session_day_kst'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_session_id', sa.String(length=64), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_attendance_program_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_attendance_program_session_id'), ['program_session_id', 'code_hash'])
        batch_op.drop_constraint(batch_op.f('fk_attendance_program_id_program'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_attendance_program_session_id_program_session'), 'program_session', ['program_session_id'], ['id'])
        batch_op.drop_column('program_id')

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('ends_at')
        batch_op.drop_column('starts_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starts_at', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('ends_at', sa.VARCHAR(length=40), nullable=False))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_attendance_program_session_id_program_session'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_attendance_program_id_program'), 'program', ['program_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_attendance_program_session_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_attendance_program_id'), ['program_id', 'code_hash', 'day_kst'])
        batch_op.drop_column('program_session_id')

    with op.batch_alter_table('program_session', schema=None) as batch_op:
        batch_op.drop_index('ix_program_session_day')

    op.drop_table('program_session')
    # ### end Alembic commands ###
