"""web_kiosk_baseline

Revision ID: d54e8c97a8a4
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd54e8c97a8a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('directions', sa.JSON(), nullable=False),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place'))
    )
    op.create_table('program',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('place_id', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.String(length=40), nullable=False),
    sa.Column('ends_at', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('instructor', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_program_place_id_place')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program'))
    )
    op.create_table('robot',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('home_place_id', sa.String(length=64), nullable=False),
    sa.Column('current_place_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['current_place_id'], ['place.id'], name=op.f('fk_robot_current_place_id_place')),
    sa.ForeignKeyConstraint(['home_place_id'], ['place.id'], name=op.f('fk_robot_home_place_id_place')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_robot'))
    )
    op.create_table('attendance',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('day_kst', sa.String(length=10), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_attendance_program_id_program')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('program_id', 'code_hash', 'day_kst', name=op.f('uq_attendance_program_id'))
    )
    op.create_table('trip',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('robot_id', sa.String(length=64), nullable=False),
    sa.Column('destination_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint("status IN ('requested','moving','arrived','canceled','failed')", name=op.f('ck_trip_status')),
    sa.ForeignKeyConstraint(['destination_id'], ['place.id'], name=op.f('fk_trip_destination_id_place')),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], name=op.f('fk_trip_robot_id_robot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip'))
    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.create_index('uq_trip_robot_active', ['robot_id'], unique=True, sqlite_where=sa.text("status IN ('requested','moving')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index('uq_trip_robot_active', sqlite_where=sa.text("status IN ('requested','moving')"))

    op.drop_table('trip')
    op.drop_table('attendance')
    op.drop_table('robot')
    op.drop_table('program')
    op.drop_table('place')
    # ### end Alembic commands ###
